backup, sys_install: Update backup scripts to reflect most recent changes

diff --git a/backup b/backup
--- a/backup
+++ b/backup
@@ -149,12 +149,17 @@ ctt() {
 
 # Copy from ~
 pushd "$HOME" &> /dev/null || die "cd to $HOME failed"
+
+# update .gitconfig and .profile_private into pass
+cat .gitconfig | pass insert -m .gitconfig > /dev/null || die 'copying .gitconfig into pass failed'
+cat .profile_private | pass insert -m .profile_private > /dev/null || die 'copying .profile_private into pass failed'
+
 if [[ ! -e "$target/.m2" ]]; then
   mkdir "$target/.m2" || die "mkdir .m2 failed"
 fi
 
 rm -rf .gnupg/S.gpg-agent* #remove rsync-blocking sockets from gpg-agent (timeout for retyping key password)
-ctt .bashrc .profile .zshrc .nanorc .m2/settings.xml .tm_properties .ssh .password-store .gnupg
+ctt .bashrc .profile .profile_public .zshrc .nanorc .m2/settings.xml .tm_properties .ssh .password-store .gnupg
 
 # read -p "Do you want to continue backup with the time consuming folders? (y/n) [y]: " ans
 # case $ans in
