backup: Function resorting

diff --git a/backup b/backup
--- a/backup
+++ b/backup
@@ -12,6 +12,10 @@ $usage
 	\e[1m-c\e[0m	Calculate needed space for backup.
 "
 
+####################################################
+### Functions
+####################################################
+
 die() {
   echo "ERROR: $*" >&2
   exit 1
@@ -67,6 +71,54 @@ calc_size() {
   return $return_code
 }
 
+function rsyncit() {
+  rsync $rsync_progress --size-only --recursive --filter=':- .gitignore' \
+          --links --perms --times --crtimes --group --owner --devices --specials `# preserve everything` \
+          --delete --delete-delay `# but delete non existing files` \
+          "$1" "$2"; return $?
+}
+
+function ctt() { #copy to target
+  while [[ -n "$1" ]]; do
+    source_name="$1"
+    shift
+    echo "Backing up $PWD/$source_name (calculating size ..."
+    size=$(calc_size "$PWD/$source_name") || continue;
+    printf "\e[F\e[KBacking up $PWD/$source_name (%s) ...\n" "${size:-??}"
+    if [[ -d "$source_name" ]]; then
+      rsyncit "$source_name/" "$target/$source_name" || {
+        warn "Backing up folder $source_name to $target failed"
+        continue;
+      }
+    elif [[ -f "$source_name" ]]; then
+      rsyncit "$source_name" "$target/$source_name" || {
+        warn "Backing up file $source_name to $target failed"
+        continue;
+      }
+    else
+      warn "Invalid backup task: $source_name"
+      continue;
+    fi
+  done
+}
+
+function createTargetDir() {
+  if [[ ! -d "$target/$1" ]]; then
+    if [[ -e "$target/$1" ]]; then
+      echo "Already exists, but is not a directory: $target/$1"
+      echo "Removing ..."
+      rm -rf "$target/$1" || die "rm $target/$1 failed"
+    fi
+    mkdir "$target/$1" || die "mkdir $target/$1 failed"
+  fi
+}
+
+function saveToPass() {
+  filename=$(basename "$1")
+  echo "Save $filename to pass"
+  cat "$1" | pass insert -m "$filename" > /dev/null || die "Copying $filename into pass failed"
+}
+
 ####################################################
 ### Args parsing
 ####################################################
@@ -105,11 +157,9 @@ case $1 in
     ;;
 esac
 
-function saveToPass() {
-  filename=$(basename "$1")
-  echo "Save $filename to pass"
-  cat "$1" | pass insert -m "$filename" > /dev/null || die "Copying $filename into pass failed"
-}
+####################################################
+### Preparation: Make backup of backup
+####################################################
 
 # for convenience reasons, place here
 # update .gitconfig and .private_profile into pass
@@ -125,10 +175,6 @@ if [[ -z "$target" ]]; then
   exit 1
 fi
 
-####################################################
-### Preparation: Make backup of backup
-####################################################
-
 if [[ -d "$target" ]]; then
   echo "Backing up current backup (calculating size ..."
   size=$(calc_size "$target") || die "Size calculation for $target failed"
@@ -141,49 +187,6 @@ fi
 ####################################################
 ### Backup
 ####################################################
-
-function rsyncit() {
-  rsync $rsync_progress --size-only --recursive --filter=':- .gitignore' \
-          --links --perms --times --crtimes --group --owner --devices --specials `# preserve everything` \
-          --delete --delete-delay `# but delete non existing files` \
-          "$1" "$2"; return $?
-}
-
-#copy to target
-function ctt() {
-  while [[ -n "$1" ]]; do
-    source_name="$1"
-    shift
-    echo "Backing up $PWD/$source_name (calculating size ..."
-    size=$(calc_size "$PWD/$source_name") || continue;
-    printf "\033[A\rBacking up $PWD/$source_name (%s) ...\n" "${size:-??}"
-    if [[ -d "$source_name" ]]; then
-      rsyncit "$source_name/" "$target/$source_name" || {
-        warn "Backing up folder $source_name to $target failed"
-        continue;
-      }
-    elif [[ -f "$source_name" ]]; then
-      rsyncit "$source_name" "$target/$source_name" || {
-        warn "Backing up file $source_name to $target failed"
-        continue;
-      }
-    else
-      warn "Invalid backup task: $source_name"
-      continue;
-    fi
-  done
-}
-
-function createTargetDir() {
-  if [[ ! -d "$target/$1" ]]; then
-    if [[ -e "$target/$1" ]]; then
-      echo "Already exists, but is not a directory: $target/$1"
-      echo "Removing ..."
-      rm -rf "$target/$1" || die "rm $target/$1 failed"
-    fi
-    mkdir "$target/$1" || die "mkdir $target/$1 failed"
-  fi
-}
 
 # Copy from ~
 pushd "$HOME" &> /dev/null || die "cd to $HOME failed"
