clat: Allow compilation in other directories than ./

diff --git a/clat b/clat
--- a/clat
+++ b/clat
@@ -64,6 +64,7 @@ while [[ $1 == -* ]]; do
 done
 
 goal="${1:-$default_name}"
+goal_dir=$(dirname "$goal")
 [[ -n "$2" ]] && multiple=true || multiple=
 
 if [[ -z $SHORT ]] && ! cat "$goal" | grep '\\ref' &>/dev/null; then
@@ -78,15 +79,15 @@ elif [[ -n "$goal" ]]; then
     echo "Please give an existing and readable file. See -h for more help."
     exit 1
   fi
-  pdflatex "$goal" || die 'First latex compilation run failed'
+  pdflatex -output-directory "$goal_dir" "$goal" || die 'First latex compilation run failed'
   if [[ $SHORT == "false" ]]; then
     if cat "$goal" | grep '^\\printbibliography' >/dev/null; then
       biber "${goal:0:$((${#goal}-4))}"
     else
       bibtex "${goal:0:$((${#goal}-3))}aux"
     fi
-    pdflatex "$goal" || die 'Second latex compilation run failed'
-    pdflatex "$goal" || die 'Third latex compilation run failed'
+    pdflatex -output-directory "$goal_dir" "$goal" || die 'Second latex compilation run failed'
+    pdflatex -output-directory "$goal_dir" "$goal" || die 'Third latex compilation run failed'
   fi
   open_it "$goal"
 else
