sys_install: Add missing .m2 dir creation

diff --git a/sys_install b/sys_install
--- a/sys_install
+++ b/sys_install
@@ -255,6 +255,9 @@ if [[ -z "$IT" ]]; then # $IT is required by script
   # install .bash_profile as root
   c -s .bash_profile
   # install the other shit
+  if [[ ! -d .m2 ]]; then
+    mkdir .m2 || die "mkdir $HOME/.m2 failed!"
+  fi
   c .m2/settings.xml .tm_properties .ssh .password-store .gnupg
 
   #install terminal layouts
