sys_install: Install graphing calculator from nativefier

diff --git a/sys_install b/sys_install
--- a/sys_install
+++ b/sys_install
@@ -43,6 +43,7 @@ nv_directory="$C/Apps/NV"
 templates="$C/Org/Vorlagen"
 # resources
 duolingo_icon="$IT/duolingo.jpg" # icon for Duolingo.app
+graphing_icon="$IT/graphing calculator.jpg" # icon for Graphing Calculator.app
 trading_icon="$PROJ/212/js-listener/trading212.png" # icon for Trading212.app
 trading_script="$PROJ/212/js-listener/212listener.js" # listener for Trading212.app
 firefox_bookmark_backup="$thisdir/files/firefox_bookmark.jsonlz4"
@@ -864,7 +865,7 @@ echo "All required cloud data available"
 if [[ ! -e "/Applications/Duolingo.app" ]]; then
   echo "### Duolingo.app installation"
   echo "Installing Duolingo.app with nativefier from https://www.duolingo.com/learn"
-  nativefier -n "Duolingo" -i "$duolingo_icon" "https://www.duolingo.com/learn" || die "Creating Duolingo.app failed"
+  nativefier -f -n "Duolingo" -i "$duolingo_icon" https://www.duolingo.com/learn || die "Creating Duolingo.app failed"
   mv "Duolingo-darwin-x64/Duolingo.app" /Applications/
   rm -rf "Duolingo-darwin-x64"
   echo
@@ -872,11 +873,23 @@ else
   echo "Skipped creation of Duolingo.app with nativefier"
 fi
 
+# create Graphing Calculator.app with nativefier
+if [[ ! -e "/Applications/Graphing Calculator.app" ]]; then
+  echo "### Graphing Calculator.app installation"
+  echo "Installing Graphing Calculator.app with nativefier from https://www.desmos.com/calculator"
+  nativefier -f -n "Graphing Calculator" -i "$graphing_icon" https://www.desmos.com/calculator || die "Creating Graphing Calculator.app failed"
+  mv "Graphing Calculator-darwin-x64/Graphing Calculator.app" /Applications/
+  rm -rf "Graphing Calculator-darwin-x64"
+  echo
+else
+  echo "Skipped creation of Graphing Calculator.app with nativefier"
+fi
+
 # create WhatsAppWeb.app with nativefier
 if [[ ! -e "/Applications/WhatsApp Web.app" ]]; then
   echo "### Whatsapp Web.app installation"
   echo "Installing Whatsapp Web.app with nativefier from http://web.whatsapp.com/"
-  nativefier -n "WhatsApp Web" "http://web.whatsapp.com/" || die "Creating Whatsapp Web.app failed"
+  nativefier -f -n "WhatsApp Web" http://web.whatsapp.com/ || die "Creating Whatsapp Web.app failed"
   mv "WhatsApp Web-darwin-x64/WhatsApp Web.app" /Applications/
   rm -rf "WhatsApp Web-darwin-x64"
   echo
@@ -888,7 +901,7 @@ fi
 if [[ ! -e "/Applications/Trading212.app" ]]; then
   echo "### Trading212.app installation"
   echo "Installing Trading212.app with nativefier from https://www.trading212.com/"
-  nativefier -i "$trading_icon" --inject "$trading_script" -n "Trading212" 'https://www.trading212.com/' || die "Creating Trading212.app failed"
+  nativefier -f -i "$trading_icon" --inject "$trading_script" -n "Trading212" https://www.trading212.com/ || die "Creating Trading212.app failed"
 
   mv "Trading212-darwin-x64/Trading212.app" /Applications/ || die "Moving to /Applications/ failed"
   rm -rf "Trading212-darwin-x64"
