unmount: Make kill signal explicit

diff --git a/unmount b/unmount
--- a/unmount
+++ b/unmount
@@ -1,5 +1,7 @@
 #!/bin/bash
 
+KILL_SIGNAL=TERM
+
 function die() {
   mes=$1
   shift
@@ -30,6 +32,7 @@ else
 fi
 
 function unmount0() {
+  sync
   if [[ "$1" =~ disk.*s.* ]]; then
     diskutil unmount "$1"
   else
@@ -43,12 +46,12 @@ else
   if [[ "$volume" =~ disk* && -n $(echo "$disks" | grep -- "$volume") ]]; then
     res=$(unmount0 "$volume" 2>&1)
     echo "$res"
-    pid=$(echo "$res" | grep -oE "PID \d+" | cut -d ' ' -f 2)
+    pid=$(echo "$res" | grep -m 1 -oE "PID \d+" | cut -d ' ' -f 2)
     if [[ -n $pid ]]; then
       ps -p $pid
-      read -p "Do you want to kill this process (PID $pid)? (y/n) [y]: " ans2
+      read -p "Do you want to kill ($KILL_SIGNAL) this process (PID $pid)? (y/n) [y]: " ans2
       if [[ -z $ans2 || $ans2 == y ]]; then
-        kill $pid || die "Failed to kill process PID $pid"
+        kill -$KILL_SIGNAL $pid || die "Failed to kill ($KILL_SIGNAL) process PID $pid"
         unmount0 "$volume"
       else
         echo "Nothing killed. Try again later."
