yt: Fix a long series of bugs

diff --git a/yt b/yt
--- a/yt
+++ b/yt
@@ -1,11 +1,11 @@
 #!/bin/bash
 
 DEBUG=""
-youtube="https://www.youtube.com/"
+youtube="https://www.youtube.com"
 site=""
 query=""
-RESULTS=""
-RESULTSCNT=0
+declare -a LINKS
+declare -a RESULTS
 usage="Usage: \e[1m$(basename $0)\e[0m -h | -l | \e[4msite\e[0m [\e[4mseries\e[0m] | -u \e[4muser\e[0m [\e[4mseries\e[0m] | \e[4mquery\e[0m \e[4m...\e[0m"
 help="Commandline interaction with YouTube.
 $usage
@@ -38,7 +38,7 @@ while [[ -n $1 ]]; do
       echo "Please give a user name with option -u. See -h for more help."
       exit 1
     }
-    site="${youtube}user/${1}/videos"
+    site="${youtube}/user/${1}/videos"
     ;;
   -c)
     shift
@@ -46,7 +46,7 @@ while [[ -n $1 ]]; do
       echo "Please give a channel with option -c. See -h for more help."
       exit 1
     }
-    site="${youtube}channel/${1}/videos"
+    site="${youtube}/channel/${1}/videos"
     ;;
   -*)
     printf "Wrong argument: %s\n$usage -- See -h for more help.\n" "$1"
@@ -64,7 +64,61 @@ while [[ -n $1 ]]; do
   shift
 done
 
-# write videos from youtube site $1, filtered by optional query $2, into global variable $RESULTS
+function parseLinks0() {
+  echo "$1" | pup --charset utf8 "div h3 a[title*=${2}I]" | grep -o 'href="/watch?v=[^"]*' | sed 's/href="/https:\/\/www.youtube.com/'
+}
+
+function parseLinks() {
+  # https://developer.mozilla.org/en-US/docs/Web/CSS/Attribute_selectors
+  local tmp_links=$(parseLinks0 "$1" "$2")
+  if [[ -n $DEBUG ]]; then
+    local all_links=$(parseLinks0 "$1" "")
+    printf "All links:\n%s\n" "$all_links"
+    printf "Filtered links:\n%s\n" "$LINKS"
+  fi
+  LINKS=(${tmp_links})
+}
+
+function parseResults0() {
+  local json=$(echo "$1" | pup --charset utf8 '.yt-lockup-content json{}')
+  node -e "
+    const json = JSON.parse(process.argv[1]);
+    for (let el of json) {
+      const title = el.children[0].children;
+      if ('$2' && title[0].text.toLowerCase().indexOf('$2'.toLowerCase()) === -1) continue;
+      //console.error(title[0].text)
+      const info = el.children[1].children[0].children;
+      console.log(title[0].text + ' \033[2m' + title[1].text + '\033[0m \033[37m' + info[1].text + ' \033[2m' + info[0].text + '\033[0m')
+      console.log('$youtube' + title[0].href)
+    }" "$json" \
+    | perl -MHTML::Entities -pe 'decode_entities($_);'
+}
+
+function parseResults() {
+  local tmp_parsed=$(parseResults0 "$1" "$2")
+  local tmp_results=$(echo "$tmp_parsed" | sed -n 'p;n')
+  IFS=$'\n' RESULTS=(${tmp_results})
+  local tmp_links=$(echo "$tmp_parsed" | sed -n '1d;p;n')
+  IFS=$'\n' LINKS=(${tmp_links})
+
+  if [[ -n $DEBUG ]]; then
+    local all_results=$(parseResults0 "$1")
+    printf "All results:\n%s\n" "$all_results"
+    printf "Filtered results:\n%s\n" "$tmp_parsed"
+  fi
+
+  if [[ ${#RESULTS[@]} -eq 0 ]]; then
+    if [[ -n $2 ]]; then
+      echo "No results found for \"$2\". Try another."
+      exit 1
+    else
+      echo "No results found. Probably a script failure."
+      exit 1
+    fi
+  fi
+}
+
+# fetch videos from youtube site $1, filtered by optional query $2
 function fetchVideos() {
   waitnet -s || exit 1
   local src=$(curl -sS "$1")
@@ -87,66 +141,45 @@ function fetchVideos() {
       exit 1
     fi
 
-    local links=$(echo "$content" | pup --charset utf8 "div h3 a[title*=$2]" | grep -o 'href="/watch?v=[^"]*' | sed 's/href="/https:\/\/www.youtube.com/')
-    #echo "$links"
-    local json=$(echo "$content" | pup --charset utf8 '.yt-lockup-content json{}')
-    RESULTS=$(node -e "
-      const json = JSON.parse(process.argv[1]);
-      for (let el of json) {
-        const title = el.children[0].children;
-        if (\"$2\" && title[0].text.indexOf(\"$2\") === -1) continue;
-        //console.error(title[0].text)
-        const info = el.children[1].children[0].children;
-        console.log(title[0].text + ' \033[2m' + title[1].text + '\033[0m \033[37m' + info[1].text + ' \033[2m' + info[0].text + '\033[0m')
-      }" "$json" \
-      | perl -MHTML::Entities -pe 'decode_entities($_);')
+#    parseLinks "$content" "$2"
+    parseResults "$content" "$2"
 
-    RESULTSCNT=$(printf "%s" "$RESULTS" | wc -l)
-    local LINKSCNT=$(printf "%s" "$links" | wc -l)
-    if [[ $RESULTSCNT != $LINKSCNT ]]; then
-      printf "WTF-Error: %d titles, but %d links!\n" $RESULTSCNT $LINKSCNT
-      echo "RESULTS: $RESULTS"
-      echo "$links: $links"
+    if [[ ${#RESULTS[@]} != ${#LINKS[@]} ]]; then
+      printf "WTF-Error: %d titles, but %d links!\n" ${#RESULTS[@]} ${#LINKS[@]}
+      echo "RESULTS:"
+      printf '%s\n' "${RESULTS[@]}"
+      echo "LINKS:"
+      printf '%s\n' "${LINKS[@]}"
       exit 1
-    elif [[ $RESULTSCNT -eq 0 ]]; then
-      if [[ -n $2 ]]; then
-        echo "No results found for \"$2\". Try another."
-        exit 1
-      else
-        echo "No results found. Probably a script failure."
-        exit 1
-      fi
     fi
-
   else
     echo "Fetching from $1 failed."
     exit 1
   fi
 }
 
-printResults() {
+function printResults() {
   cnt=0
   IFS=$'\n'
-  for title in $RESULTS; do
-    ((cnt++))
-    echo "$cnt: $title"
+  for idx in "${!RESULTS[@]}"; do
+    printf "%s: %s\n" "$idx" "${RESULTS[$idx]}"
   done
 }
 
-askForChoose() {
+function askForChoose() {
   if [[ $1 = true ]]; then
     printResults
   fi
 
-  if [[ $RESULTSCNT -eq 1 ]]; then
+  if [[ ${#RESULTS[@]} -eq 1 ]]; then
     printf "Only one result found. Do you want to open it? (y/n) [y]: "
     read ans
     case $ans in
       ""|j|y|J|Y|Yes)
         if [[ -z $DEBUG ]]; then
-          f -i "$links"
+          f -i "${LINKS[0]}"
         else
-          echo "f -i $links"
+          echo "f -i ${LINKS[0]}"
         fi
       ;;
       *)
@@ -154,12 +187,12 @@ askForChoose() {
     esac
     exit 0
   else
-    printf "Which one do you want to open? (1-%d) [1]: " $RESULTSCNT
+    printf "Which one do you want to open? (1-%d) [1]: " ${#RESULTS[@]}
     read ans
     [[ -z "$ans" ]] && ans=1
     if [[ $ans =~ ^[0-9]+$ ]]; then
-      if [[ $ans -gt 0 && $ans -le $RESULTSCNT ]]; then
-        result=$(echo "$links" | sed -n "${ans}p")
+      if [[ $ans -gt 0 && $ans -le ${#RESULTS[@]} ]]; then
+        result=${LINKS[${ans}]}
         if [[ -z $DEBUG ]]; then
           f "$result"
         else
