yt: Clearer structure by function extracting. Ask for choose until first one is selected or no or only one result found.

diff --git a/yt b/yt
--- a/yt
+++ b/yt
@@ -4,6 +4,8 @@ DEBUG=""
 youtube="https://www.youtube.com/"
 site=""
 query=""
+RESULTS=""
+RESULTSLEN=0
 usage="Usage: \e[1m$(basename $0)\e[0m -h | \e[4msite\e[0m [\e[4mseries\e[0m] | -u \e[4muser\e[0m [\e[4mseries\e[0m] | \e[4mquery\e[0m \e[4m...\e[0m"
 help="Commandline interaction with YouTube.
 $usage
@@ -58,6 +60,7 @@ while [[ -n $1 ]]; do
   shift
 done
 
+# write videos from youtube site $1, filtered by optional query $2, into global variable $RESULTS
 function fetchVideos() {
   waitnet -s || exit 1
   src=$(curl -sS "$1")
@@ -83,67 +86,88 @@ function fetchVideos() {
     links=$(echo "$content" | pup --charset utf8 "div h3 a[title*=$2]" | grep -o 'href="/watch?v=[^"]*' | sed 's/href="/https:\/\/www.youtube.com/')
     #echo "$links"
     json=$(echo "$content" | pup --charset utf8 '.yt-lockup-content json{}')
-    titles=$(node -e "const json = JSON.parse(process.argv[1]);
-for (let el of json) {
-  const title = el.children[0].children;
-  if (\"$2\" && title[0].text.indexOf(\"$2\") === -1) continue;
-  //console.error(title[0].text)
-  const info = el.children[1].children[0].children;
-  console.log(title[0].text + ' \033[2m' + title[1].text + '\033[0m \033[37m' + info[1].text + ' \033[2m' + info[0].text + '\033[0m')
-}" "$json" | perl -MHTML::Entities -pe 'decode_entities($_);')
-    if [[ $(echo "$titles" | wc -l) != $(echo "$links" | wc -l) ]]; then
-      printf "WTF-Error: %d titles, but %d links!\n" $(echo "$titles" | wc -l) $(echo "$links" | wc -l)
-      echo "titles: $titles"
+    RESULTS=$(node -e "
+      const json = JSON.parse(process.argv[1]);
+      for (let el of json) {
+        const title = el.children[0].children;
+        if (\"$2\" && title[0].text.indexOf(\"$2\") === -1) continue;
+        //console.error(title[0].text)
+        const info = el.children[1].children[0].children;
+        console.log(title[0].text + ' \033[2m' + title[1].text + '\033[0m \033[37m' + info[1].text + ' \033[2m' + info[0].text + '\033[0m')
+      }" "$json" \
+      | perl -MHTML::Entities -pe 'decode_entities($_);')
+
+    RESULTSLEN=$(echo "$RESULTS" | wc -l)
+    if [[ $RESULTSLEN != $(echo "$links" | wc -l) ]]; then
+      printf "WTF-Error: %d titles, but %d links!\n" $RESULTSLEN $(echo "$links" | wc -l)
+      echo "RESULTS: $RESULTS"
       echo "$links: $links"
       exit 1
-    fi
-
-    cnt=0
-    IFS=$'\n'
-    for title in $titles; do
-      ((cnt++))
-      echo "$cnt: $title"
-    done
-
-    if [[ $cnt -eq 0 ]]; then
+    elif [[ $RESULTSLEN -eq 0 ]]; then
       if [[ -n $2 ]]; then
         echo "No results found for \"$2\". Try another."
       else
         echo "No results found. Probably a script failure."
       fi
-    elif [[ $cnt -eq 1 ]]; then
-      printf "Only one result found. Do you want to open it? (y/n) [y]: "
-      read ans
-      case $ans in
-        ""|j|y|J|Y|Yes)
-          [[ -z $DEBUG ]] && f -i "$links" || echo "f -i $links"
-        ;;
-        *)
-        ;;
-      esac
-    else
-      printf "Which one do you want to open? (1-${cnt}) [1]: "
-      read ans
-      [[ -z "$ans" ]] && ans=1
-      if [[ $ans =~ ^[0-9]+$ ]]; then
-        if [[ $ans -gt 0 && $ans -le $cnt ]]; then
-          result=$(echo "$links" | sed -n "${ans}p")
-          [[ -z $DEBUG ]] && f "$result" || echo "f $result"
-        else
-          echo "Wrong answer. Integer is zero or too high: $ans."
-        fi
-      else
-        echo "Nothing opened."
-      fi
     fi
+
   else
     echo "Fetching from $1 failed."
+  fi
+}
+
+printResults() {
+  cnt=0
+  IFS=$'\n'
+  for title in $RESULTS; do
+    ((cnt++))
+    echo "$cnt: $title"
+  done
+}
+
+askForChoose() {
+  if [[ $1 = true ]]; then
+    printResults
+  fi
+
+  if [[ $RESULTSLEN -eq 1 ]]; then
+    printf "Only one result found. Do you want to open it? (y/n) [y]: "
+    read ans
+    case $ans in
+      ""|j|y|J|Y|Yes)
+        [[ -z $DEBUG ]] && f -i "$links" || echo "f -i $links"
+      ;;
+      *)
+      ;;
+    esac
+    exit 0
+  else
+    printf "Which one do you want to open? (1-%d) [1]: " $RESULTSLEN
+    read ans
+    [[ -z "$ans" ]] && ans=1
+    if [[ $ans =~ ^[0-9]+$ ]]; then
+      if [[ $ans -gt 0 && $ans -le $RESULTSLEN ]]; then
+        result=$(echo "$links" | sed -n "${ans}p")
+        [[ -z $DEBUG ]] && f "$result" || echo "f $result"
+        [[ $ans -eq 1 ]] && exit 0
+      else
+        echo "Wrong answer. Integer is zero or too high: $ans."
+        exit 1
+      fi
+    else
+      echo "Nothing opened."
+      exit 0
+    fi
   fi
 }
 
 if [[ "$site" = ${youtube}* ]]; then
   if [[ "$site" = */videos ]]; then
     fetchVideos "$site" "$query"
+    askForChoose true
+    while true; do
+      askForChoose false
+    done
   else
     [[ -n "$query" ]] && echo "Warning: query [${query}] will be ignored"
     [[ -z $DEBUG ]] && f -i "$site" || echo "f -i $site"
