yt: Add option -u for giving user only

diff --git a/yt b/yt
--- a/yt
+++ b/yt
@@ -3,13 +3,15 @@
 DEBUG=""
 youtube="https://www.youtube.com/"
 site=""
-usage="Usage: \e[1m$(basename $0)\e[0m -h | \e[4msite\e[0m [\e[4mseries\e[0m] | \e[4mquery\e[0m \e[4m...\e[0m"
+query=""
+usage="Usage: \e[1m$(basename $0)\e[0m -h | \e[4msite\e[0m [\e[4mseries\e[0m] | -u \e[4muser\e[0m | \e[4mquery\e[0m \e[4m...\e[0m"
 help="Commandline interaction with YouTube.
 $usage
 	\e[1m-h\e[0m	Displays this message and exists.
 	\e[1m-d\e[0m	Debug mode: Don't open any link, but print it out.
 	\e[4msite\e[0m	Videos site (from user or channel) to grep videos from.
 	\e[4mseries\e[0m	Filters for special series containing \e[4mseries\e[0m (case insensitive).
+	\e[1m-u\e[0m \e[4muser\e[0m	Give a \e[4muser\e[0m name to grep videos from.
 	\e[4mquery\e[0m	Search a specified query on YouTube.
 "
 while [[ -n $1 ]]; do
@@ -20,16 +22,27 @@ while [[ -n $1 ]]; do
   ;;
   -d)
     DEBUG=true
+    ;;
+  -u)
     shift
+    [[ -z "$1" ]] && {
+      echo "Please give a user name with option -u. See -h for more help."
+      exit 1
+    }
+    site="${youtube}user/${1}/videos"
     ;;
   -*)
     printf "Wrong argument: %s\n$usage -- See -h for more help.\n" "$1"
     exit 1
   ;;
   *)
+    site=$1
+    shift
+    query="$*"
     break;
   ;;
   esac
+  shift
 done
 
 function fetchVideos() {
@@ -37,6 +50,23 @@ function fetchVideos() {
   src=$(curl -sS "$1")
   if [[ -n $src ]]; then
     content=$(echo "$src" | pup --charset utf8 '.yt-lockup-content')
+
+    # trouble shooting
+    if [[ -z "$content" ]]; then
+      channel_empty=$(echo "$src" | pup '.channel-empty-message')
+      [[ -n "$channel_empty" ]] && {
+        if [[ $1 = */user/* ]]; then
+          printf "Bad username: %s\n" $(echo "$1" | sed -e 's/.*\/user\///' -e 's/\/videos//')
+        else
+          echo "Channel does not exist: $1"
+        fi
+        exit 1
+      }
+      title=$(echo "$src" | pup --charset utf8 'title text{}')
+      echo "No content found: $title: $1"
+      exit 1
+    fi
+
     linksHTML=$(echo "$content" | pup --charset utf8 "div h3 a" | grep "$2")
     titles=$(echo "$linksHTML" | pup --charset utf8 'a attr{title}' | perl -MHTML::Entities -pe 'decode_entities($_);')
     links=$(echo "$linksHTML" | grep -o 'href="/watch?v=[^"]*' | sed 's/href="/https:\/\/www.youtube.com/')
@@ -86,16 +116,17 @@ function fetchVideos() {
       fi
     fi
   else
-    echo "Fetching from $site failed."
+    echo "Fetching from $1 failed."
   fi
 }
 
-if [[ "$1" = ${youtube}* ]]; then
-  if [[ "$1" = */videos ]]; then
-    fetchVideos "$1" "$2"
+if [[ "$site" = ${youtube}* ]]; then
+  if [[ "$site" = */videos ]]; then
+    fetchVideos "$site" "$query"
   else
-    [[ -z $DEBUG ]] && f -i "$1" || echo "f -i $1"
+    [[ -n "$query" ]] && echo "Warning: query [${query}] will be ignored"
+    [[ -z $DEBUG ]] && f -i "$site" || echo "f -i $site"
   fi
 else
-  [[ -z $DEBUG ]] && f yt "$*" || echo "f yt $*"
+  [[ -z $DEBUG ]] && f yt "$site $query" || echo "f yt $site $query"
 fi
